name: Generate Commits

on:
  schedule:
    - cron: '0 0 * * *' # Schedule to run daily at midnight

jobs:
  generate-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 # Update to v2

      - name: Set up Git
        run: |
          git config user.email "shrijan.buzz.5@gmail.com"
          git config user.name "Shrijan Bajracharya"

      - name: Set up Node.js
        uses: actions/setup-node@v3 # Update to v3
        with:
          node-version: '20' # You can specify Node.js version here

      - name: Generate Commits
        run: |
          cd $GITHUB_WORKSPACE
          num_commits=$((RANDOM % 7 + 2))
          for ((i=1; i<=$num_commits; i++)); do
              commit_message="Commit $i: $(openssl rand -base64 12)"
              echo "Update js" > "file$i.txt"
              git add .
              git commit -m "$commit_message"
          done
          git push ShriBuzz/Monster-world $GITHUB_REF
